name: contexts
on: workflow_dispatch

jobs:
    context:
        runs-on: ubuntu-latest
        steps:
        - name: github context
          run: echo '${{ toJSON(github) }}'
    context-2:
        runs-on: ubuntu-latest
        steps:
        - name: github context
          run: | 
            echo '${{ github.repository }}'
            echo '${{ github.event_name }}'