name: multiple-event-workflow
on:
    push:
    issue:
        type: [open]
    workflow_dispatch:

job:
    multiple-event-job:
        runs-on: ubuntu-latest
        steps:
        - name: step1
          run: echo hello world
        - name: step2
          run: |
           echo hello world2
           echo github action!
        - name: step3
          run: echo test!
        - name: echo inputs
          run: |
            echo ${{ inputs.name }}
            echo ${{ inputs.environment }}

